right_format = "$time"
command_timeout = 1500

[custom.sudo]
description = 'valid sudo timestamp marker'
command = "sudo -vn && echo -n '‚ö°Ô∏è'"
format = '[$symbol$output]($style) '
style = 'bold fg:bright-red'
when = 'true'

[git_status]
style = 'yellow'

[aws]
disabled = true

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style) '

[battery]
format = '[üîã $percentage]($style) '

[time]
disabled = false
format = "[$time]($style) "
style = "#008000"
time_format = "%H:%M"